# Generated by Django 4.2.1 on 2023-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmodel",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
