# Generated by Django 4.2.1 on 2023-06-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_about_social_imageabout"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
