# Generated by Django 4.2.1 on 2023-05-21 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="directions",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
