# Generated by Django 4.2.1 on 2023-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="website",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
