# Generated by Django 4.2.1 on 2023-05-31 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_comment_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
