# Generated by Django 4.2.1 on 2023-06-03 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comment_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created",
            new_name="create_at",
        ),
    ]
